# 🔢 Complete NumPy Practice Notebook
### Taught the way a teacher would explain it in class — every line commented with PURPOSE

Welcome! This notebook explains **why** NumPy exists, **what problem** it solves,
and **how** to use every major feature — with heavily commented code.

**How to use this notebook:**
1. Run cells in order (Shift + Enter).
2. Read every comment — that's the "teacher talking" part explaining the *purpose*.
3. Each section ends with **Practice Exercises** (no answers given — so you actually learn).

Let's begin! 🚀

## 0️⃣ Why does NumPy even exist?

**Purpose:** Python's built-in lists are flexible but SLOW for math and large data,
because each element is a full Python object with overhead.

**NumPy (Numerical Python)** gives us the `ndarray` — a fixed-type, densely packed
array stored in contiguous memory. This makes it:
- **Much faster** (operations run in optimized C code, not pure Python loops)
- **Memory efficient** (no per-element Python object overhead)
- **The foundation** of pandas, scikit-learn, TensorFlow, PyTorch — basically all of data science

**Rule of thumb:** if you're doing math on lots of numbers, use NumPy, not plain lists.

In [1]:
# Let's PROVE numpy is faster, so you believe it (not just take my word for it)
import numpy as np
import time

size = 1_000_000

# Method 1: plain Python list + loop
python_list = list(range(size))
start = time.time()
result_list = [x * 2 for x in python_list]
python_time = time.time() - start

# Method 2: numpy array + vectorized operation (no explicit loop!)
numpy_array = np.arange(size)
start = time.time()
result_array = numpy_array * 2
numpy_time = time.time() - start

print(f"Python list time: {python_time:.5f} seconds")
print(f"NumPy array time: {numpy_time:.5f} seconds")
print(f"NumPy is about {python_time/numpy_time:.1f}x faster!")

Python list time: 0.22636 seconds
NumPy array time: 0.03840 seconds
NumPy is about 5.9x faster!


In [2]:
# Check the version we're using (good habit before starting any project)
print("NumPy version:", np.__version__)

NumPy version: 2.4.4


## 1️⃣ Creating Arrays

**Purpose:** Before doing any math, you need to get your data INTO a NumPy array.
There are many ways depending on what you already have (a list) or what you need
to generate (zeros, ranges, random numbers, etc.)

In [3]:
# The most basic way: convert a Python list into a numpy array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)
print("Type:", type(arr1))

# A 2D array (matrix) — created from a list of lists
# PURPOSE: represents tabular/grid data, like an Excel sheet or an image
arr2 = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("\n2D array (matrix):\n", arr2)

1D array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>

2D array (matrix):
 [[1 2 3]
 [4 5 6]]


In [4]:
# np.zeros() -> creates an array filled with 0s
# PURPOSE: useful as a starting "empty" container you fill in later (e.g. initializing weights)
zeros_arr = np.zeros((2, 3))   # 2 rows, 3 columns
print("Zeros array:\n", zeros_arr)

# np.ones() -> creates an array filled with 1s
# PURPOSE: useful for masks, or multiplying/initializing counters
ones_arr = np.ones((3, 2))
print("\nOnes array:\n", ones_arr)

# np.full() -> creates an array filled with a CUSTOM value
full_arr = np.full((2, 2), 7)
print("\nFull array (filled with 7):\n", full_arr)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Full array (filled with 7):
 [[7 7]
 [7 7]]


In [5]:
# np.arange(start, stop, step) -> like Python's range(), but returns an array
# PURPOSE: quickly generate a sequence of numbers (e.g. for indexing, plotting x-axis)
seq = np.arange(0, 20, 2)   # 0 to 20 (exclusive), step 2
print("arange sequence:", seq)

# np.linspace(start, stop, num) -> generates 'num' evenly spaced numbers between start & stop
# PURPOSE: very common in plotting/math when you need N evenly spaced points (INCLUSIVE of stop)
lin = np.linspace(0, 1, 5)   # 5 numbers evenly spaced between 0 and 1
print("linspace sequence:", lin)

arange sequence: [ 0  2  4  6  8 10 12 14 16 18]
linspace sequence: [0.   0.25 0.5  0.75 1.  ]


In [6]:
# np.eye() -> creates an Identity Matrix (1s on diagonal, 0s elsewhere)
# PURPOSE: used heavily in linear algebra (e.g. as a "do nothing" transformation matrix)
identity = np.eye(4)
print("Identity matrix:\n", identity)

# np.random -> generates random numbers
# PURPOSE: used for simulations, testing, initializing machine learning model weights
np.random.seed(42)  # seed makes randomness REPRODUCIBLE (same output every run — important for teaching/debugging!)
random_arr = np.random.rand(3, 3)   # random floats between 0 and 1
print("\nRandom array:\n", random_arr)

random_ints = np.random.randint(1, 100, size=(2, 4))  # random integers between 1 and 100
print("\nRandom integers:\n", random_ints)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random array:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

Random integers:
 [[24  3 22 53]
 [ 2 88 30 38]]


### 📝 Practice Exercise 1
1. Create a 1D array with numbers 10 to 50 (step 5) using `arange`
2. Create a 3x3 array of all zeros
3. Create 10 evenly spaced numbers between 0 and 100 using `linspace`
4. Create a 4x4 random integer array with values between 1 and 20 (set a seed first!)

In [7]:
# ✅ Exercise 1 Solution

# 1. 1D array from 10 to 50 (inclusive), counting up by 5
ex1_a = np.arange(10, 51, 5)   # stop is 51, not 50, because arange's stop is EXCLUSIVE
print("1)", ex1_a)

# 2. 3x3 array of all zeros
ex1_b = np.zeros((3, 3))
print("2)\n", ex1_b)

# 3. 10 evenly spaced numbers between 0 and 100 (linspace INCLUDES both ends)
ex1_c = np.linspace(0, 100, 10)
print("3)", ex1_c)

# 4. 4x4 random integers between 1 and 20
# PURPOSE of the seed: makes the "random" numbers repeatable every time we run this cell
np.random.seed(1)
ex1_d = np.random.randint(1, 21, size=(4, 4))   # 21 because randint's high is EXCLUSIVE
print("4)\n", ex1_d)


1) [10 15 20 25 30 35 40 45 50]
2)
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
3) [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
4)
 [[ 6 12 13  9]
 [10 12  6 16]
 [ 1 17  2 13]
 [ 8 14  7 19]]


## 2️⃣ Array Properties — Knowing Your Data

**Purpose:** Before working with an array, always check its shape, size, and type.
This prevents 90% of beginner bugs (like trying to add arrays of mismatched shapes).

In [8]:
sample = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# .shape -> tuple showing (rows, columns) -> ALWAYS check this first!
print("Shape:", sample.shape)

# .ndim -> number of dimensions (1D, 2D, 3D...)
print("Number of dimensions:", sample.ndim)

# .size -> total number of elements
print("Total elements:", sample.size)

# .dtype -> the data type stored (int64, float64, etc.)
# PURPOSE: knowing dtype matters for memory usage and precision
print("Data type:", sample.dtype)

# .itemsize -> memory (in bytes) used by EACH element
print("Bytes per element:", sample.itemsize)

Shape: (3, 4)
Number of dimensions: 2
Total elements: 12
Data type: int64
Bytes per element: 8


### 📝 Practice Exercise 2
1. Create any 2x5 array
2. Print its shape, ndim, size, and dtype
3. Convert it to `dtype=float` using `.astype(float)` and print the new dtype

In [9]:
# ✅ Exercise 2 Solution

# 1. Any 2x5 array (2 rows, 5 columns)
ex2 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10]])

# 2. Check the array's basic properties
print("Shape:", ex2.shape)   # (rows, columns)
print("ndim:", ex2.ndim)     # number of dimensions
print("size:", ex2.size)     # total number of elements
print("dtype:", ex2.dtype)   # data type of the elements (likely int64)

# 3. Convert to float dtype and confirm the change
ex2_float = ex2.astype(float)
print("New dtype after astype(float):", ex2_float.dtype)


Shape: (2, 5)
ndim: 2
size: 10
dtype: int64
New dtype after astype(float): float64


## 3️⃣ Indexing & Slicing

**Purpose:** You constantly need to grab specific elements, rows, columns, or sub-sections
of an array — for example, extracting one feature column from a dataset.

In [10]:
arr = np.array([10, 20, 30, 40, 50])

# Basic indexing (0-based, just like Python lists)
print("First element:", arr[0])
print("Last element:", arr[-1])

# Slicing: arr[start:stop:step]
print("Elements 1 to 3:", arr[1:4])
print("Every other element:", arr[::2])
print("Reversed array:", arr[::-1])

First element: 10
Last element: 50
Elements 1 to 3: [20 30 40]
Every other element: [10 30 50]
Reversed array: [50 40 30 20 10]


In [11]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# 2D indexing: matrix[row, column]
print("Element at row 1, col 2:", matrix[1, 2])   # = 6

# Selecting a full ROW
print("Row 0:", matrix[0])

# Selecting a full COLUMN (: means "all rows")
print("Column 1:", matrix[:, 1])

# Selecting a SUB-MATRIX (slice both rows and columns)
print("Top-left 2x2 block:\n", matrix[0:2, 0:2])

Element at row 1, col 2: 6
Row 0: [1 2 3]
Column 1: [2 5 8]
Top-left 2x2 block:
 [[1 2]
 [4 5]]


In [12]:
# Boolean indexing (VERY important, used constantly in data science)
# PURPOSE: filter an array to keep only elements matching a condition
data = np.array([5, 12, 8, 20, 3, 17])

mask = data > 10          # creates a True/False array
print("Boolean mask:", mask)

filtered = data[mask]     # keep only elements where mask is True
print("Elements > 10:", filtered)

# Shortcut: do it in one line
print("Same thing in one line:", data[data > 10])

Boolean mask: [False  True False  True False  True]
Elements > 10: [12 20 17]
Same thing in one line: [12 20 17]


In [13]:
# Fancy indexing -> select multiple specific elements using a LIST of indices
# PURPOSE: grab specific, non-contiguous elements at once (e.g. specific rows you care about)
arr = np.array([100, 200, 300, 400, 500])
selected = arr[[0, 2, 4]]   # get elements at positions 0, 2, and 4
print("Selected elements:", selected)

Selected elements: [100 300 500]


### 📝 Practice Exercise 3
1. Create an array of numbers 1 to 20
2. Print only the elements at even indices using slicing
3. Print only the elements that are divisible by 3 (boolean indexing)
4. Create a 4x4 matrix (any numbers) and print its 2nd column and last row

In [14]:
# ✅ Exercise 3 Solution

# 1. Array of numbers 1 to 20
ex3 = np.arange(1, 21)
print("1) Full array:", ex3)

# 2. Elements at EVEN indices (index 0, 2, 4, ...) using step-2 slicing
#    NOTE: "even index" is not the same as "even number" — index 0 holds the value 1!
print("2) Even-index elements:", ex3[::2])

# 3. Elements divisible by 3, using boolean indexing
print("3) Divisible by 3:", ex3[ex3 % 3 == 0])

# 4. A 4x4 matrix, then its 2nd column and last row
matrix4 = np.arange(1, 17).reshape(4, 4)
print("4) Matrix:\n", matrix4)
print("   2nd column (index 1):", matrix4[:, 1])   # ':' means "all rows"
print("   Last row:", matrix4[-1])                  # -1 means "last row"


1) Full array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2) Even-index elements: [ 1  3  5  7  9 11 13 15 17 19]
3) Divisible by 3: [ 3  6  9 12 15 18]
4) Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
   2nd column (index 1): [ 2  6 10 14]
   Last row: [13 14 15 16]


## 4️⃣ Vectorized Math Operations

**Purpose:** This is NumPy's biggest strength — apply math to an ENTIRE array at once,
with no explicit `for` loop needed. This is called **vectorization** and it's both
faster to run AND faster to write.

In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Element-wise operations (each position operates with the matching position)
print("Addition:      ", a + b)
print("Subtraction:   ", b - a)
print("Multiplication:", a * b)
print("Division:      ", b / a)
print("Power:         ", a ** 2)

# Operating with a single number (called "broadcasting" — explained more below)
print("\nAdd 100 to every element:", a + 100)
print("Multiply every element by 3:", a * 3)

Addition:       [11 22 33 44]
Subtraction:    [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division:       [10. 10. 10. 10.]
Power:          [ 1  4  9 16]

Add 100 to every element: [101 102 103 104]
Multiply every element by 3: [ 3  6  9 12]


In [16]:
# Useful math functions built into numpy (all vectorized -> fast!)
arr = np.array([1, 4, 9, 16, 25])

print("Square root:", np.sqrt(arr))
print("Exponential (e^x):", np.exp(a))
print("Natural log:", np.log(arr))
print("Absolute value:", np.abs(np.array([-5, -2, 3, -8])))
print("Round:", np.round(np.array([1.234, 5.678]), 1))  # round to 1 decimal place

Square root: [1. 2. 3. 4. 5.]
Exponential (e^x): [ 2.71828183  7.3890561  20.08553692 54.59815003]
Natural log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Absolute value: [5 2 3 8]
Round: [1.2 5.7]


### 📝 Practice Exercise 4
1. Create two arrays of 5 numbers each
2. Compute and print their sum, difference, and product (element-wise)
3. Create an array of 5 numbers and compute the square root and square of each

In [17]:
# ✅ Exercise 4 Solution

# 1. Two arrays of 5 numbers each
a4 = np.array([1, 2, 3, 4, 5])
b4 = np.array([10, 20, 30, 40, 50])

# 2. Element-wise sum, difference, and product (no loops needed — this is vectorization!)
print("Sum:", a4 + b4)
print("Difference:", a4 - b4)
print("Product:", a4 * b4)

# 3. Square root and square of a 5-number array
c4 = np.array([1, 4, 9, 16, 25])
print("Square root:", np.sqrt(c4))
print("Square:", c4 ** 2)


Sum: [11 22 33 44 55]
Difference: [ -9 -18 -27 -36 -45]
Product: [ 10  40  90 160 250]
Square root: [1. 2. 3. 4. 5.]
Square: [  1  16  81 256 625]


## 5️⃣ Aggregation Functions (Summarizing Data)

**Purpose:** Instead of looking at every individual number, we often want ONE summary
number that describes the whole array — total, average, highest, lowest, etc.
This is the foundation of statistics and data analysis.

In [18]:
scores = np.array([85, 90, 78, 92, 88, 76, 95])

print("Sum:", np.sum(scores))
print("Mean (average):", np.mean(scores))
print("Median:", np.median(scores))
print("Standard deviation:", np.std(scores))   # measures how spread out the data is
print("Variance:", np.var(scores))
print("Minimum:", np.min(scores))
print("Maximum:", np.max(scores))

# argmin/argmax -> gives the INDEX (position) of the min/max, not the value itself
# PURPOSE: useful when you need to know WHICH student got the highest score, not just the score
print("\nIndex of highest score:", np.argmax(scores))
print("Index of lowest score:", np.argmin(scores))

Sum: 604
Mean (average): 86.28571428571429
Median: 88.0
Standard deviation: 6.562105187346201
Variance: 43.06122448979592
Minimum: 76
Maximum: 95

Index of highest score: 6
Index of lowest score: 5


In [19]:
# Aggregations on a 2D array — you can choose the AXIS to summarize along
# PURPOSE: e.g. "total sales per product" (sum along rows) vs "total sales per day" (sum along columns)
sales = np.array([[100, 200, 150],   # Day 1 sales for 3 products
                   [120, 180, 160],   # Day 2 sales
                   [90,  210, 140]])  # Day 3 sales

print("Total of everything:", np.sum(sales))

# axis=0 -> collapse ROWS -> gives column sums (total per PRODUCT across all days)
print("Sum per column (axis=0):", np.sum(sales, axis=0))

# axis=1 -> collapse COLUMNS -> gives row sums (total per DAY across all products)
print("Sum per row (axis=1):", np.sum(sales, axis=1))

Total of everything: 1350
Sum per column (axis=0): [310 590 450]
Sum per row (axis=1): [450 460 440]


### ⚠️ Teacher's Tip (Important Gotcha!)
`axis=0` means "go DOWN the rows" (collapses rows → gives you column results).
`axis=1` means "go ACROSS the columns" (collapses columns → gives you row results).
Every beginner mixes these up at first — now you know it in advance! 😉

### 📝 Practice Exercise 5
1. Create an array of 10 random integers (1-100). Print mean, median, std, min, max
2. Find the INDEX of the maximum value
3. Create a 3x3 matrix and print the sum along axis=0 and axis=1 separately

In [20]:
# ✅ Exercise 5 Solution

# 1. 10 random integers between 1 and 100, then key summary statistics
np.random.seed(2)   # seed for reproducible "random" results
ex5 = np.random.randint(1, 101, 10)
print("Data:", ex5)
print("Mean:", ex5.mean())
print("Median:", np.median(ex5))
print("Std dev:", ex5.std())
print("Min:", ex5.min())
print("Max:", ex5.max())

# 2. Index (position) of the maximum value, not the value itself
print("Index of max value:", np.argmax(ex5))

# 3. 3x3 matrix, sum along each axis
matrix5 = np.arange(1, 10).reshape(3, 3)
print("Matrix:\n", matrix5)
print("Sum axis=0 (down each column):", matrix5.sum(axis=0))
print("Sum axis=1 (across each row):", matrix5.sum(axis=1))


Data: [41 16 73 23 44 83 76  8 35 50]
Mean: 44.9
Median: 42.5
Std dev: 24.545671716210986
Min: 8
Max: 83
Index of max value: 5
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum axis=0 (down each column): [12 15 18]
Sum axis=1 (across each row): [ 6 15 24]


## 6️⃣ Reshaping Arrays

**Purpose:** Data often needs to be reshaped to fit what a function expects —
for example, converting a flat list of pixel values into a proper image grid,
or turning a row into a column for matrix math.

In [21]:
arr = np.arange(12)   # array of 0 to 11 (12 elements)
print("Original:", arr)

# reshape(rows, cols) -> the total elements MUST match (12 = 3*4 = 4*3 = 2*6 etc.)
reshaped = arr.reshape(3, 4)
print("\nReshaped to 3x4:\n", reshaped)

reshaped2 = arr.reshape(4, 3)
print("\nReshaped to 4x3:\n", reshaped2)

# Using -1 tells numpy "figure this dimension out automatically"
# PURPOSE: convenient when you know one dimension but not the other
auto_reshape = arr.reshape(2, -1)   # 2 rows, columns auto-calculated (=6)
print("\nReshaped to 2 rows, auto columns:\n", auto_reshape)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to 4x3:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Reshaped to 2 rows, auto columns:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [22]:
# .flatten() -> converts ANY shape back into a single 1D array
# PURPOSE: useful before feeding data into models that expect flat input
matrix = np.array([[1, 2, 3], [4, 5, 6]])
flat = matrix.flatten()
print("Flattened:", flat)

# .T -> Transpose (flips rows and columns)
# PURPOSE: essential in linear algebra / matrix multiplication where dimensions must align
print("\nOriginal matrix:\n", matrix)
print("\nTransposed matrix:\n", matrix.T)

Flattened: [1 2 3 4 5 6]

Original matrix:
 [[1 2 3]
 [4 5 6]]

Transposed matrix:
 [[1 4]
 [2 5]
 [3 6]]


### 📝 Practice Exercise 6
1. Create an array with `arange(16)` and reshape it into a 4x4 matrix
2. Flatten that matrix back into 1D
3. Transpose a 2x3 matrix of your choice and print before/after shapes

In [23]:
# ✅ Exercise 6 Solution

# 1. arange(16) reshaped into a 4x4 matrix (16 = 4*4, so it fits perfectly)
matrix6 = np.arange(16).reshape(4, 4)
print("4x4 matrix:\n", matrix6)

# 2. Flatten it back into a single 1D array
flat6 = matrix6.flatten()
print("Flattened back to 1D:", flat6)

# 3. Transpose a 2x3 matrix and compare shapes before/after
matrix6b = np.arange(6).reshape(2, 3)
print("Before transpose, shape:", matrix6b.shape)   # (2, 3)
print("After transpose, shape:", matrix6b.T.shape)   # (3, 2) -> rows and columns swap


4x4 matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Flattened back to 1D: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Before transpose, shape: (2, 3)
After transpose, shape: (3, 2)


## 7️⃣ Broadcasting — NumPy's Secret Superpower

**Purpose:** Broadcasting lets NumPy perform operations between arrays of
DIFFERENT shapes, by automatically "stretching" the smaller one — without
actually copying data in memory (very efficient!).

This is why we could earlier do `a + 100` even though `100` isn't an array.

In [24]:
# Example: add a different number to EACH COLUMN of a matrix
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

col_adjustment = np.array([10, 20, 30])  # shape (3,) -> matches the number of COLUMNS

# NumPy automatically broadcasts col_adjustment across every row
result = matrix + col_adjustment
print("Matrix + column adjustment:\n", result)

# This is equivalent to manually doing this to EVERY row (but broadcasting does it for free):
# [1+10, 2+20, 3+30]
# [4+10, 5+20, 6+30]
# [7+10, 8+20, 9+30]

Matrix + column adjustment:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


### ⚠️ Broadcasting Rule (memorize this!)
Two shapes are compatible for broadcasting if, comparing from the RIGHT side:
- the dimensions are equal, OR
- one of them is 1 (or missing)

Example: shape `(3,3)` and shape `(3,)` → compatible (3==3 on the right)
Example: shape `(3,3)` and shape `(2,)` → **NOT compatible** → will throw an error!

In [25]:
# Let's PROVE the error happens, so you recognize it when it does
try:
    bad = np.array([[1,2,3],[4,5,6]]) + np.array([1, 2])  # shapes (2,3) and (2,) don't align on the right
except ValueError as e:
    print("Got the expected error:", e)

Got the expected error: operands could not be broadcast together with shapes (2,3) (2,) 


### 📝 Practice Exercise 7
1. Create a 4x3 matrix of any numbers
2. Create a 1D array of 3 numbers (matches the columns)
3. Add them together using broadcasting and print the result
4. Try adding a 1D array of 4 numbers instead and observe the error

In [26]:
# ✅ Exercise 7 Solution

# 1. A 4x3 matrix
matrix7 = np.arange(12).reshape(4, 3)
print("Matrix (4x3):\n", matrix7)

# 2. A 1D array of 3 numbers (matches the 3 COLUMNS of matrix7)
vec7 = np.array([100, 200, 300])

# 3. Broadcasting adds vec7 to EVERY row automatically (no loop needed!)
print("Matrix + row vector (broadcasted):\n", matrix7 + vec7)

# 4. Now try a 1D array of 4 numbers instead -> shapes (4,3) and (4,) do NOT
#    align on the right-most dimension, so this raises a ValueError
try:
    bad_vec = np.array([1, 2, 3, 4])
    matrix7 + bad_vec
except ValueError as e:
    print("Got the expected broadcasting error:", e)


Matrix (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Matrix + row vector (broadcasted):
 [[100 201 302]
 [103 204 305]
 [106 207 308]
 [109 210 311]]
Got the expected broadcasting error: operands could not be broadcast together with shapes (4,3) (4,) 


## 8️⃣ Linear Algebra Essentials

**Purpose:** NumPy has built-in linear algebra functions used constantly in
machine learning, graphics, physics simulations, and statistics.

In [27]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Element-wise multiplication (NOT true matrix multiplication!)
print("Element-wise multiply (A * B):\n", A * B)

# TRUE matrix multiplication -> use @ or np.dot()
# PURPOSE: this is the real "matrix multiplication" from linear algebra class
print("\nMatrix multiplication (A @ B):\n", A @ B)
print("\nSame using np.dot():\n", np.dot(A, B))

Element-wise multiply (A * B):
 [[ 5 12]
 [21 32]]

Matrix multiplication (A @ B):
 [[19 22]
 [43 50]]

Same using np.dot():
 [[19 22]
 [43 50]]


In [28]:
# Determinant -> a single number describing properties of a square matrix
# PURPOSE: used to check if a matrix is invertible (det=0 means NOT invertible)
det = np.linalg.det(A)
print("Determinant of A:", det)

# Inverse -> the matrix that "undoes" A (like a reciprocal, but for matrices)
inv = np.linalg.inv(A)
print("\nInverse of A:\n", inv)

# Proof: A multiplied by its inverse gives the identity matrix
print("\nA @ A_inverse (should be close to identity):\n", np.round(A @ inv))

Determinant of A: -2.0000000000000004

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

A @ A_inverse (should be close to identity):
 [[1. 0.]
 [0. 1.]]


### 📝 Practice Exercise 8
1. Create two 2x2 matrices of your choice
2. Compute their matrix product using `@`
3. Compute the determinant and inverse of one of them

In [29]:
# ✅ Exercise 8 Solution

# 1. Two 2x2 matrices
A8 = np.array([[1, 2],
                [3, 4]])
B8 = np.array([[2, 0],
                [1, 2]])

# 2. TRUE matrix multiplication uses @ (NOT the same as A8 * B8, which is element-wise!)
product8 = A8 @ B8
print("A @ B:\n", product8)

# 3. Determinant and inverse of A8
det8 = np.linalg.det(A8)
inv8 = np.linalg.inv(A8)
print("Determinant of A:", det8)
print("Inverse of A:\n", inv8)


A @ B:
 [[ 4  4]
 [10  8]]
Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## 9️⃣ Useful Utility Functions

**Purpose:** These functions solve extremely common everyday tasks:
conditional replacement, sorting, and finding unique values.

In [30]:
arr = np.array([15, 3, 42, 8, 23, 4, 16])

# np.sort() -> returns a NEW sorted array (doesn't change the original)
print("Sorted:", np.sort(arr))
print("Original unchanged:", arr)

# np.where(condition, value_if_true, value_if_false)
# PURPOSE: like Excel's IF() function, applied to an entire array at once
labels = np.where(arr > 10, "High", "Low")
print("\nLabels based on condition:", labels)

# np.unique() -> returns sorted UNIQUE values, removes duplicates
duplicates = np.array([1, 2, 2, 3, 3, 3, 4])
print("\nUnique values:", np.unique(duplicates))

# np.unique with return_counts -> also tells you HOW MANY times each value appears
values, counts = np.unique(duplicates, return_counts=True)
print("Values:", values)
print("Counts:", counts)

Sorted: [ 3  4  8 15 16 23 42]
Original unchanged: [15  3 42  8 23  4 16]

Labels based on condition: ['High' 'Low' 'High' 'Low' 'High' 'Low' 'High']

Unique values: [1 2 3 4]
Values: [1 2 3 4]
Counts: [1 2 3 1]


### 📝 Practice Exercise 9
1. Create an unsorted array of 8 numbers and sort it
2. Use `np.where()` to label each number as "Even" or "Odd"
3. Create an array with repeated values and find the unique values + their counts

In [31]:
# ✅ Exercise 9 Solution

# 1. An unsorted array of 8 numbers, then sorted (np.sort returns a NEW array)
arr9 = np.array([8, 3, 9, 1, 5, 2, 7, 4])
print("Original:", arr9)
print("Sorted:", np.sort(arr9))

# 2. Label each number "Even" or "Odd" using np.where (like Excel's IF, applied to the whole array)
labels9 = np.where(arr9 % 2 == 0, "Even", "Odd")
print("Even/Odd labels:", labels9)

# 3. An array with repeated values -> find unique values AND how many times each appears
dup9 = np.array([1, 1, 2, 3, 3, 3, 4])
unique_vals, counts = np.unique(dup9, return_counts=True)
print("Unique values:", unique_vals)
print("Counts:       ", counts)


Original: [8 3 9 1 5 2 7 4]
Sorted: [1 2 3 4 5 7 8 9]
Even/Odd labels: ['Even' 'Odd' 'Odd' 'Odd' 'Odd' 'Even' 'Odd' 'Even']
Unique values: [1 2 3 4]
Counts:        [2 1 3 1]


## 🏆 Final Challenge — Put It All Together

**Scenario:** You are analyzing temperature readings (in Celsius) recorded
every hour for 3 days (72 readings total).

1. Generate 72 random temperature readings between 15 and 40 using `np.random.randint` (set a seed = 1 first)
2. Reshape the data into a (3, 24) array — 3 days, 24 hours each
3. Find the average temperature PER DAY (hint: which axis?)
4. Find the average temperature PER HOUR across all 3 days (hint: which axis?)
5. Find the single hottest reading and which day+hour it occurred (`np.argmax` + `np.unravel_index`)
6. Convert every reading from Celsius to Fahrenheit using the formula `F = C * 9/5 + 32` (vectorized, no loop!)
7. Use `np.where()` to label each reading as "Hot" (>30°C) or "Normal"

*(This combines array creation, reshaping, aggregation with axis, broadcasting, and conditional logic — everything from this notebook!)*

In [32]:
# ✅ Final Challenge Solution

# 1. 72 random temperature readings between 15 and 40 (40 is exclusive in randint, so use 41)
np.random.seed(1)
temps = np.random.randint(15, 41, 72)

# 2. Reshape into (3, 24): 3 days, 24 hours each
temps_grid = temps.reshape(3, 24)
print("Temperature grid (3 days x 24 hours):\n", temps_grid)

# 3. Average temperature PER DAY -> collapse across the hours (columns) -> axis=1
avg_per_day = temps_grid.mean(axis=1)
print("\nAverage temperature per day:", avg_per_day)

# 4. Average temperature PER HOUR across all days -> collapse across the days (rows) -> axis=0
avg_per_hour = temps_grid.mean(axis=0)
print("Average temperature per hour (across 3 days):", avg_per_hour)

# 5. Hottest single reading, and which day/hour it happened at
hottest_index = np.argmax(temps_grid)                       # flat (1D) index of the max value
day, hour = np.unravel_index(hottest_index, temps_grid.shape)  # convert flat index -> (row, col)
print(f"\nHottest reading: {temps_grid.max()}°C on day {day + 1}, hour {hour}")

# 6. Convert every reading from Celsius to Fahrenheit (vectorized -> applies to the whole array at once)
temps_fahrenheit = temps_grid * 9 / 5 + 32
print("\nTemperatures in Fahrenheit:\n", temps_fahrenheit)

# 7. Label each reading "Hot" (>30°C) or "Normal"
heat_labels = np.where(temps_grid > 30, "Hot", "Normal")
print("\nHot/Normal labels:\n", heat_labels)


Temperature grid (3 days x 24 hours):
 [[20 26 27 23 24 26 20 30 15 31 16 27 22 28 21 40 33 35 20 33 35 26 25 29]
 [33 19 38 38 24 32 38 15 37 28 24 24 22 37 40 16 15 32 23 39 28 34 30 25]
 [40 23 22 18 21 36 32 40 18 19 39 32 26 27 35 31 28 34 24 33 30 15 19 40]]

Average temperature per day: [26.33333333 28.79166667 28.41666667]
Average temperature per hour (across 3 days): [31.         22.66666667 29.         26.33333333 23.         31.33333333
 30.         28.33333333 23.33333333 26.         26.33333333 27.66666667
 23.33333333 30.66666667 32.         29.         25.33333333 33.66666667
 22.33333333 35.         31.         25.         24.66666667 31.33333333]

Hottest reading: 40°C on day 1, hour 15

Temperatures in Fahrenheit:
 [[ 68.   78.8  80.6  73.4  75.2  78.8  68.   86.   59.   87.8  60.8  80.6
   71.6  82.4  69.8 104.   91.4  95.   68.   91.4  95.   78.8  77.   84.2]
 [ 91.4  66.2 100.4 100.4  75.2  89.6 100.4  59.   98.6  82.4  75.2  75.2
   71.6  98.6 104.   60.8  59.   8


Hot/Normal labels:
 [['Normal' 'Normal' 'Normal' 'Normal' 'Normal' 'Normal' 'Normal' 'Normal'
  'Normal' 'Hot' 'Normal' 'Normal' 'Normal' 'Normal' 'Normal' 'Hot' 'Hot'
  'Hot' 'Normal' 'Hot' 'Hot' 'Normal' 'Normal' 'Normal']
 ['Hot' 'Normal' 'Hot' 'Hot' 'Normal' 'Hot' 'Hot' 'Normal' 'Hot' 'Normal'
  'Normal' 'Normal' 'Normal' 'Hot' 'Hot' 'Normal' 'Normal' 'Hot' 'Normal'
  'Hot' 'Normal' 'Hot' 'Normal' 'Normal']
 ['Hot' 'Normal' 'Normal' 'Normal' 'Normal' 'Hot' 'Hot' 'Hot' 'Normal'
  'Normal' 'Hot' 'Hot' 'Normal' 'Normal' 'Hot' 'Hot' 'Normal' 'Hot'
  'Normal' 'Hot' 'Normal' 'Normal' 'Normal' 'Hot']]


---
## 🎉 Congratulations!

If you completed all the exercises above, you now understand:
- ✅ Why NumPy exists and why it's fast (vectorization)
- ✅ Creating arrays (zeros, ones, arange, linspace, random)
- ✅ Array properties (shape, ndim, size, dtype)
- ✅ Indexing, slicing, boolean & fancy indexing
- ✅ Vectorized math operations & built-in functions
- ✅ Aggregations and the `axis` parameter
- ✅ Reshaping, flattening, and transposing
- ✅ Broadcasting rules
- ✅ Linear algebra basics (matrix multiplication, determinant, inverse)
- ✅ Utility functions: `sort`, `where`, `unique`

**Next steps:** Move on to Pandas (which is BUILT on top of NumPy), then explore
`np.random` distributions and NumPy's role in machine learning libraries.

*Made with ❤️ for learning NumPy — practice daily, and you'll master it fast.*